"""Generate Renki's grain-stalk mark.

Parametrised because the shape has to be judged by measurement rather than by
eye here: an app icon wants a mark that roughly fills its square, so the
bounding box is a design constraint, not an afterthought.
"""
import math, sys, pathlib

STEM_X, STEM_TOP, STEM_BOTTOM, STEM_W = 256, 240, 430, 24
GRAIN_L, GRAIN_W = 140, 68          # length and width of one grain
PAIRS = [(304, 60), (248, 60), (192, 60)]   # (pivot y, splay degrees)
CROWN_Y = 96

def grain(cx, tip_y, base_y, half_w):
    """A pointed almond from base to tip, `half_w` at its widest."""
    mid = (tip_y + base_y) / 2
    return (f"M{cx} {base_y} "
            f"C{cx + half_w} {mid} {cx + half_w} {mid - (base_y - tip_y) * 0.28} {cx} {tip_y} "
            f"C{cx - half_w} {mid - (base_y - tip_y) * 0.28} {cx - half_w} {mid} {cx} {base_y} Z")

parts = [
    f'<rect x="{STEM_X - STEM_W/2}" y="{STEM_TOP}" width="{STEM_W}" height="{STEM_BOTTOM - STEM_TOP}" rx="{STEM_W/2}"/>',
    f'<path d="{grain(STEM_X, CROWN_Y, CROWN_Y + GRAIN_L, GRAIN_W/2)}"/>',
]
for pivot_y, splay in PAIRS:
    d = grain(STEM_X, pivot_y - GRAIN_L, pivot_y, GRAIN_W / 2)
    for sign in (1, -1):
        parts.append(f'<path d="{d}" transform="rotate({sign * splay} {STEM_X} {pivot_y})"/>')

svg = ('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" width="512" height="512">\n'
       '  <!--\n'
       "    Renki's mark: a stalk of grain.\n\n"
       '    The name is Finnish for a hired farmhand, so the mark is the crop rather\n'
       "    than the worker — something that grows while you aren't watching it, which\n"
       '    is what a session on your own server does. One silhouette, no thin strokes\n'
       '    and no interior detail, so it survives being a 16px favicon.\n'
       '\n'
       '    Generated by assets-src/make-mark.py — edit the parameters there.\n'
       '  -->\n'
       '  <g fill="currentColor">\n    ' + "\n    ".join(parts) + '\n  </g>\n</svg>\n')
pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else "assets-src/mark.svg").write_text(svg)

# The ink's own bounds, so callers can place the mark without guessing how much
# empty room the 512 canvas leaves around it (measured: it fills 47% x 65%).
half = GRAIN_W / 2
reach = GRAIN_L * math.sin(math.radians(max(s for _, s in PAIRS))) + half
x0, x1 = STEM_X - reach, STEM_X + reach
y0, y1 = CROWN_Y, STEM_BOTTOM
tight = svg.replace('viewBox="0 0 512 512"', f'viewBox="{x0:.0f} {y0:.0f} {x1-x0:.0f} {y1-y0:.0f}"', 1)
pathlib.Path("assets-src/mark-tight.svg").write_text(tight)
print(f"wrote mark; tight viewBox {x1-x0:.0f}x{y1-y0:.0f}")
